import { sqliteTable, text, integer, real } from "drizzle-orm/sqlite-core";

export const admins = sqliteTable("admins", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  email: text("email").notNull().unique(),
  passwordHash: text("password_hash").notNull(),
  name: text("name").notNull(),
  createdAt: text("created_at").notNull().$defaultFn(() => new Date().toISOString()),
});

export const properties = sqliteTable("properties", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull(),
  address1: text("address1").notNull(),
  city: text("city").notNull(),
  state: text("state").notNull(),
  zip: text("zip").notNull(),
  monthlyRent: real("monthly_rent").notNull(),
  securityDeposit: real("security_deposit").notNull(),
  leaseType: text("lease_type").notNull().default("fixed"),
  status: text("status").notNull().default("available"),
  leaseTermsSummary: text("lease_terms_summary"),
  createdAt: text("created_at").notNull().$defaultFn(() => new Date().toISOString()),
  updatedAt: text("updated_at").notNull().$defaultFn(() => new Date().toISOString()),
});

export const prescreenings = sqliteTable("prescreenings", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  propertyId: integer("property_id").references(() => properties.id),
  fullName: text("full_name").notNull(),
  phone: text("phone").notNull(),
  email: text("email").notNull(),
  dateOfBirth: text("date_of_birth"),
  currentAddress: text("current_address"),
  desiredMoveIn: text("desired_move_in").notNull(),
  adultsCount: integer("adults_count").notNull(),
  childrenCount: integer("children_count").notNull().default(0),
  occupantNames: text("occupant_names"),
  monthlyIncome: real("monthly_income").notNull(),
  creditScoreRange: text("credit_score_range").notNull(),
  employmentStatus: text("employment_status").notNull(),
  employerName: text("employer_name"),
  jobTitle: text("job_title"),
  employmentLength: text("employment_length"),
  incomeSources: text("income_sources"),
  canProvideProofOfIncome: integer("can_provide_proof_of_income", { mode: "boolean" }).notNull(),
  meetsIncomeRequirement: integer("meets_income_requirement", { mode: "boolean" }).notNull(),
  canPayMoveIn: integer("can_pay_move_in", { mode: "boolean" }).notNull(),
  latePayments: integer("late_payments", { mode: "boolean" }).notNull().default(false),
  latePaymentsExplanation: text("late_payments_explanation"),
  housingStatus: text("housing_status").notNull(),
  currentLandlordName: text("current_landlord_name"),
  currentLandlordPhone: text("current_landlord_phone"),
  currentRent: real("current_rent"),
  currentAddressDuration: text("current_address_duration"),
  hasRentedBefore: integer("has_rented_before", { mode: "boolean" }),
  priorEviction: integer("prior_eviction", { mode: "boolean" }).notNull(),
  evictionExplanation: text("eviction_explanation"),
  brokenLease: integer("broken_lease", { mode: "boolean" }).notNull().default(false),
  askedToMoveOut: integer("asked_to_move_out", { mode: "boolean" }).notNull().default(false),
  landlordDebt: integer("landlord_debt", { mode: "boolean" }).notNull(),
  propertyDamageHistory: integer("property_damage_history", { mode: "boolean" }).notNull().default(false),
  rentalHistoryExplanation: text("rental_history_explanation"),
  hasPets: integer("has_pets", { mode: "boolean" }).notNull(),
  petsJson: text("pets_json"),
  smoking: integer("smoking", { mode: "boolean" }).notNull(),
  willingToMaintain: integer("willing_to_maintain", { mode: "boolean" }).notNull(),
  willingToHandleUtilities: integer("willing_to_handle_utilities", { mode: "boolean" }).notNull(),
  intentToSublease: integer("intent_to_sublease", { mode: "boolean" }).notNull(),
  intentToAirbnb: integer("intent_to_airbnb", { mode: "boolean" }).notNull(),
  fullTimeResidence: integer("full_time_residence", { mode: "boolean" }).notNull(),
  violentCrime: integer("violent_crime", { mode: "boolean" }).notNull().default(false),
  propertyCrime: integer("property_crime", { mode: "boolean" }).notNull().default(false),
  backgroundExplanation: text("background_explanation"),
  screeningConsent: integer("screening_consent", { mode: "boolean" }).notNull(),
  moveReason: text("move_reason"),
  additionalNotes: text("additional_notes"),
  score: integer("score"),
  status: text("status").notNull().default("new"),
  adminNotes: text("admin_notes"),
  createdAt: text("created_at").notNull().$defaultFn(() => new Date().toISOString()),
  updatedAt: text("updated_at").notNull().$defaultFn(() => new Date().toISOString()),
});

export const tenants = sqliteTable("tenants", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  propertyId: integer("property_id").references(() => properties.id),
  fullName: text("full_name").notNull(),
  email: text("email"),
  phone: text("phone"),
  moveInDate: text("move_in_date"),
  moveOutDate: text("move_out_date"),
  monthlyRent: real("monthly_rent").notNull(),
  depositRequired: real("deposit_required").notNull(),
  depositPaid: real("deposit_paid").notNull().default(0),
  leaseStatus: text("lease_status").notNull().default("active"),
  notes: text("notes"),
  createdAt: text("created_at").notNull().$defaultFn(() => new Date().toISOString()),
  updatedAt: text("updated_at").notNull().$defaultFn(() => new Date().toISOString()),
});

export const leaseTerms = sqliteTable("lease_terms", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  propertyId: integer("property_id").references(() => properties.id).notNull(),
  leaseStart: text("lease_start"),
  leaseEnd: text("lease_end"),
  monthlyRent: real("monthly_rent").notNull(),
  lateFeeRule: text("late_fee_rule"),
  securityDeposit: real("security_deposit"),
  petsAllowed: integer("pets_allowed", { mode: "boolean" }).default(false),
  petFee: real("pet_fee"),
  petRent: real("pet_rent"),
  utilitiesTerms: text("utilities_terms"),
  maintenanceTerms: text("maintenance_terms"),
  smokingTerms: text("smoking_terms"),
  showingNoticeTerms: text("showing_notice_terms"),
  specialTerms: text("special_terms"),
  createdAt: text("created_at").notNull().$defaultFn(() => new Date().toISOString()),
  updatedAt: text("updated_at").notNull().$defaultFn(() => new Date().toISOString()),
});

export const payments = sqliteTable("payments", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  tenantId: integer("tenant_id").references(() => tenants.id).notNull(),
  propertyId: integer("property_id").references(() => properties.id).notNull(),
  dueDate: text("due_date").notNull(),
  amountDue: real("amount_due").notNull(),
  amountPaid: real("amount_paid").notNull().default(0),
  paymentDate: text("payment_date"),
  paymentMethod: text("payment_method"),
  status: text("status").notNull().default("unpaid"),
  lateFee: real("late_fee").default(0),
  notes: text("notes"),
  createdAt: text("created_at").notNull().$defaultFn(() => new Date().toISOString()),
  updatedAt: text("updated_at").notNull().$defaultFn(() => new Date().toISOString()),
});

export const deposits = sqliteTable("deposits", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  tenantId: integer("tenant_id").references(() => tenants.id).notNull(),
  propertyId: integer("property_id").references(() => properties.id).notNull(),
  depositRequired: real("deposit_required").notNull(),
  depositPaid: real("deposit_paid").notNull().default(0),
  paidDate: text("paid_date"),
  refundAmount: real("refund_amount"),
  refundDate: text("refund_date"),
  deductions: text("deductions"),
  notes: text("notes"),
  createdAt: text("created_at").notNull().$defaultFn(() => new Date().toISOString()),
  updatedAt: text("updated_at").notNull().$defaultFn(() => new Date().toISOString()),
});

export const maintenanceRequests = sqliteTable("maintenance_requests", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  propertyId: integer("property_id").references(() => properties.id),
  tenantName: text("tenant_name").notNull(),
  tenantPhone: text("tenant_phone"),
  tenantEmail: text("tenant_email"),
  title: text("title").notNull(),
  description: text("description").notNull(),
  category: text("category").notNull(),
  priority: text("priority").notNull().default("medium"),
  status: text("status").notNull().default("open"),
  adminNotes: text("admin_notes"),
  createdAt: text("created_at").notNull().$defaultFn(() => new Date().toISOString()),
  updatedAt: text("updated_at").notNull().$defaultFn(() => new Date().toISOString()),
});
